### ISSUE TITLE
Interaction how to implement

### ISSUE THREAD

**Issue by ericxin1982** [Microwawe/mamba-ui#100]
Hi @Microwawe 

As I saw issues you replied to others you mentioned the component just html + css, what is the suggestion or advice how to do js interaction you would give to the end users?

Thanks
Eric Xin

**Comment by Microwawe** [comment]
Hey, 

I don't think I can give you any specific advice because that depends a lot on what component you are using and what interaction you are trying to add. 😅 
And even after that it still depends on what framework you are using (if any).

But all the components are just html + css because there are so many ways to add the interactivity and I don't have a way to add it in every style, so I chose to leave that out. The components are "just" a way to get a basic UI built easier and the rest of the details are up to the user.

**Comment by ericxin1982** [comment]
ok
