### ISSUE TITLE
Menus don't work on movile

### ISSUE THREAD

**Issue by neondeex** [Microwawe/mamba-ui#59]
Hi the menus doesn't work on mobile when you try to click the burger nothing happens

**Comment by Microwawe** [comment]
Hi!

Do you mean the burger menus on the [header components](https://mambaui.com/components/header)? 

The components in Mamba UI don't have any javascript in them (all the components are just HTML and Tailwind CSS) so yes those won't do anything and there isn't even the html for the list of menu items. I decided to leave it to the user because there are so many ways to create the dropdown menu.
